# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SigninCart' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SigninCart
	pod 'Cartography'
  target 'SigninCartTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SigninCartUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
